[build]
command = "npx prisma generate && remix build"
publish = "public"

[dev]
command = "remix watch"
port = 3000

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]

"Cache-Control" = "public, max-age=31560000, immutable"
